### ISSUE TITLE
#9 根拠のある名前決定ロジックを実装したい

### ISSUE THREAD

**Issue by hoqqun** [hoqqun/samurainame#10]
現在、

1. 入力してもらった名前をalphabet順の番号数値に変換し合算
Ai => 1 + 8 = 9 のように

2. 誕生日付を合算
1986-03-05 => 1986 + 03 + 05 = 1994

3. 上記を合算
9 + 1994 = 2005

4. 性別よりテーブルを選択し、格納されている最大レコード件数で余りを算出
2005 % 最大レコード件数 = レコードID

5. レコードIDのデータを表示する

みたいな感じで作ってます。
ただ占い的な要素をつけてあげると根拠づけられて納得感が持てるのかなと思ってます。
そこを考えたい。

**Comment by Shigeyuki-fukuda** [comment]
詳しく読んでないですが、占い系の実装で参考になるかも！
https://qiita.com/wing-x/items/f577eb3e0f4a8f7977ca

**Comment by hoqqun** [comment]
タロットカードの実装ぽいですね。参考にします！。

今日ちょっとこのサービスの話を友人と話してたんですが、
イニシャルが同じ名前を取得する
example. David だったら 大吾(Daigo)

にするのがいいんでないかという話題になりました。

どうでしょう？おそらくそれだけだと命名がかぶりまくりので、
誕生日を使って、振り分ける感じでしょうか。
