### ISSUE TITLE
#8 faviconの作成

### ISSUE THREAD

**Issue by hoqqun** [hoqqun/samurainame#9]
やること

* faviconの作成
  * faviconのロゴイメージは侍っぽければなんでもOK

[faviconの実装方法 rails](https://qiita.com/yimajo/items/981c71ca4b2048f96270)

**Comment by Shigeyuki-fukuda** [comment]
参考サイト
http://flat-icon-design.com/?p=264

これとかいかがでしょう？？
![f_f_event_67_s64_f_event_67_2bg](https://user-images.githubusercontent.com/27620649/36651423-3a64cc6c-1aec-11e8-8770-132a801cf0c3.png)

**Comment by hoqqun** [comment]
ええっすね！。探してくるもののセンスがいいっすね！。

**Comment by Shigeyuki-fukuda** [comment]
伊達政宗っぽくて良いなと思って挙げさせていただきました！！
センス褒められるの嬉しいっす！あざます:metal:

**Comment by Shigeyuki-fukuda** [comment]
じゃあこのfaviconでやっちゃいますね:+1:

**Comment by hoqqun** [comment]
ありがとうございます！。
